# Generated by Django 2.2.6 on 2019-11-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
